import React from 'react'
import Footer from '.'

const PrivacyPolicy = () => {
  return (
    <>
      <div className="container mx-auto px-4 sm:px-24 py-8 text-gray-800">
        <h1 className="text-2xl md:text-4xl font-bold mb-6 text-center text-black">
          Privacy Policy
        </h1>
        <p className="mb-6 text-start text-lg text-gray-500 font-medium">
          This Privacy Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="mb-6 text-start text-lg text-gray-500 font-medium">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <section className="mb-6">
          <h2 className="text-xl md:text-3xl font-bold mb-4 text-black">
            Interpretation and Definitions
          </h2>
          <h3 className="text-lg md:text-2xl font-bold mb-2 text-black">
            Interpretation
          </h3>
          <p className="text-lg text-gray-500 font-medium">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
          <h3 className="text-lg md:text-2xl font-bold mb-2 text-black mt-4">
            Definitions
          </h3>
          <ul className="pl-5 space-y-4 text-lg text-gray-500 font-medium">
            <li>
              <strong className="text-gray-600 text-xl">Account:</strong> means
              a unique account created for You to access our Service or parts of
              our Service.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Affiliate:</strong>{" "}
              means an entity that controls, is controlled by or is under
              common control with a party, where “control” means ownership of
              50% or more of the shares, equity interest or other securities
              entitled to vote for the election of directors or other managing
              authority.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Company:</strong>{" "}
              (referred to as either “the Company”, “We”, “Us” or “Our” in this
              Agreement) refers to 3zbio.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Cookies:</strong> are
              small files that are placed on Your computer, mobile device or any
              other device by a website, containing the details of Your browsing
              history on that website among its many uses.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Country:</strong> refers
              to Colorado, United States.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Device:</strong> means
              any device that can access the Service such as a computer, a
              cellphone, or a digital tablet.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Personal Data:</strong>{" "}
              is any information that relates to an identified or identifiable
              individual.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Service:</strong> refers
              to the Website.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Service Provider:</strong> 
              means any natural or legal person who processes the data on behalf of the Company. 
              It refers to third-party companies or individuals employed by the Company to facilitate 
              the Service, to provide the Service on behalf of the Company, to perform services related 
              to the Service or to assist the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Usage Data:</strong> refers to data 
              collected automatically, either generated by the use of the Service or from the Service 
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Website:</strong> refers to 3zbio, 
              accessible from <a href="https://www.3zbio.com" className="text-blue-500 no-underline">https://www.3zbio.com</a>.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">You:</strong> means the individual accessing or using the Service, 
              or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </section>

        <section className="mb-6">
          <h2 className="text-xl md:text-3xl font-bold mb-4 text-black">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="text-lg md:text-2xl font-bold mb-2 text-black">
            Types of Data Collected
          </h3>

          <h4 className="text-lg md:text-xl font-bold mb-2 text-black">
            Personal Data
          </h4>
          <p className="text-lg text-gray-500 font-medium">
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="pl-5 space-y-4 text-lg text-gray-500 font-medium">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-lg md:text-xl font-bold mb-2 text-black mt-4">
            Usage Data
          </h4>
          <p className="text-lg text-gray-500 font-medium">
            Usage Data is collected automatically when using the Service.
          </p>
          <p className="text-lg text-gray-500 font-medium">
            Usage Data may include information such as Your Device’s Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers, and
            other diagnostic data.
          </p>
          <p className="text-lg text-gray-500 font-medium">
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <p className="text-lg text-gray-500 font-medium">
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl md:text-3xl font-bold mb-4 text-black">
            Tracking Technologies and Cookies
          </h2>
          <p className="text-lg text-gray-500 font-medium">
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include:
          </p>
          <ul className="pl-5 space-y-4 text-lg text-gray-500 font-medium">
            <li>
              <strong className="text-gray-600 text-xl">Cookies or Browser Cookies:</strong> 
              A cookie is a small file placed on Your Device. You can instruct Your browser to refuse 
              all Cookies or to indicate when a Cookie is being sent. However, if You do not accept 
              Cookies, You may not be able to use some parts of our Service. Unless you have adjusted 
              Your browser setting so that it will refuse Cookies, our Service may use Cookies.
            </li>
            <li>
              <strong className="text-gray-600 text-xl">Web Beacons:</strong> 
              Certain sections of our Service and our emails may contain small electronic files 
              known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) 
              that permit the Company, for example, to count users who have visited those pages or opened 
              an email and for other related website statistics (for example, recording the popularity of a certain 
              section and verifying system and server integrity).
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl md:text-3xl font-bold mb-4 text-black">
            Contact Us
          </h2>
          <p className="text-lg text-gray-500 font-medium">
            If you have any questions about this Privacy Policy, You can contact
            us:
          </p>
          <ul className="pl-5 space-y-4 text-lg text-gray-500 font-medium">
            <li>
              By email:{" "}
              <a
                href="mailto:contact@3zbio.com"
                className="text-blue-500 no-underline"
              >
                contact@3zbio.com
              </a>
            </li>
          </ul>
        </section>
      </div>
      <Footer />
    </>
  )
}

export default PrivacyPolicy
